name: hw-fingertree
version: '0.1.0.1'
synopsis: Generic finger-tree structure, with example instances
description: ! 'A general sequence representation with arbitrary

  annotations, for use as a base for implementations of

  various collection types, with examples, as described

  in section 4 of


  * Ralf Hinze and Ross Paterson,

  \"Finger trees: a simple general-purpose data structure\",

  /Journal of Functional Programming/ 16:2 (2006) pp 197-217.

  <http://staff.city.ac.uk/~ross/papers/FingerTree.html>


  For a tuned sequence type, see @Data.Sequence@ in the

  @containers@ package, which is a specialization of

  this structure.'
category: Data Structures

maintainer: John Ky <newhoggy@gmail.com>
copyright:
- (c) 2006 Ross Paterson
- Ralf Hinze
- (c) 2017-2018 John Ky
license: BSD3
github: haskell-works/hw-fingertree
bug-reports: https://github.com/haskell-works/hw-fingertree/issues

dependencies:
- deepseq

library:
  source-dirs: src
  dependencies:
  - base <6

tests:
  hw-fingertree-tests:
    source-dirs:
    - tests
    - src
    main: Spec.hs
    cpp-options: -DTESTING
    dependencies:
    - base >=4.2 && <6
    - HUnit
    - hspec
    - hedgehog
    - hw-hspec-hedgehog
    - hw-fingertree
    - QuickCheck
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
